### ISSUE TITLE
Enable Hotkeys for Standard Game Functionality

### ISSUE THREAD

**Issue by hone** [hone/dragncards-mc-plugin#2]
- [x] Flip Card
- [x] Exhaust
- [x] Shuffle into Owner's Deck
- [x] Remove all tokens
- [x] Deal Encounter Card
- [x] Deal Boost Card
- [x] Draw Card
- [x] Mulligan
- [x] Ready all Cards
- [x] Discard Random Card
- [x] Discard Card
  - [x] Any Card
  - [x] Villain
  - [x] Main Scheme

**Comment by seastan** [comment]
I'm working on a test script that will make developing these a lot easier

**Comment by seastan** [comment]
Target Card will be a Dragn Hotkey, so this is not a plugin issue.
