### ISSUE TITLE
Nothing under Plugin Options (i.e. no button to change mode to expert/standard)

### ISSUE THREAD

**Issue by owen-yeung** [hone/dragncards-mc-plugin#61]

**Comment by owen-yeung** [comment]
![Uploading Screenshot 2024-04-05 at 11.05.39 AM.png…]()

**Comment by owen-yeung** [comment]
<img width="1017" alt="Screenshot 2024-04-05 at 11 05 39 AM" src="https://github.com/hone/dragncards-mc-plugin/assets/77765487/27f4ef6c-ccca-4f24-95a0-a7e4a443a9ca">

**Comment by TheGregTanaka** [comment]
@owen-yeung You can use Shift+Tab to open a menu of preferences. This allows you to select Standard/Expert, along with which standard/expert sets to use, and whether to auto-load recommended mods.

**Comment by hone** [comment]
yeah, these plugin options have now moved to preferences. Going to close this issue.
